"""Initial migration

Revision ID: 58eca37e93e5
Revises: be4931479483
Create Date: 2024-08-31 23:03:51.168715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58eca37e93e5'
down_revision = 'be4931479483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('message')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_message_chat_id')
        batch_op.drop_index('idx_message_sender_id')

    with op.batch_alter_table('user_chat', schema=None) as batch_op:
        batch_op.drop_index('idx_user_chat_chat_id')
        batch_op.drop_index('idx_user_chat_user_id')

    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.drop_index('idx_user_status_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_username', ['username'], unique=False)

    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.create_index('idx_user_status_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user_chat', schema=None) as batch_op:
        batch_op.create_index('idx_user_chat_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_chat_chat_id', ['chat_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('idx_message_chat_id', ['chat_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='message_recipient_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
